### ISSUE TITLE
Polishing 

### ISSUE THREAD

**Issue by kisasexypantera94** [kisasexypantera94/bonfire#1]
## Tasks:
- [ ] NACK
  - [ ] Client-Signaler
  - [ ] Signaler-Transcoder
- [ ] Forcing keyframes
  - [ ] Client
  - [ ] Transcoder
- [ ] More decomposition on Signaler
- [ ] Double check cleanup routines
- [ ] Stereo Opus
- [ ] docker-compose deploy
  - [ ] caching ```go mod download```
  - [ ] Figure out which ports to forward

**Comment by kisasexypantera94** [comment]
A jitterbuffer (packet re-ordering) is required for NACK to work correctly between the browser and Pion, because sequence numbers and timestamps are being incrementally set. Transcoding is working fine because it has its own jitterbuffer. That is, we must either implement a jitterbuffer on the pion side, or, regardless of the situation, send all packets through the transcoder
